language: cpp

addons:
  apt_packages:
    - libgl1-mesa-dev

matrix:
  include:

  - name: "Linux gcc"
    os: linux
    dist: xenial
    compiler: gcc
    env:
      - AMALGAMATED=OFF
  
  - name: "Linux gcc Amalgamated"
    os: linux
    dist: xenial
    compiler: gcc
    env:
      - AMALGAMATED=ON

  - name: "Linux clang"
    os: linux
    dist: xenial
    compiler: clang
    env:
      - AMALGAMATED=OFF

  - name: "Linux clang Amalgamated"
    os: linux
    dist: xenial
    compiler: clang
    env:
      - AMALGAMATED=ON

  - name: "macOS Xcode 10"
    os: osx
    osx_image: xcode10
    env:
      - AMALGAMATED=OFF

  - name: "macOS Xcode 10 Amalgamated"
    os: osx
    osx_image: xcode10
    env:
      - AMALGAMATED=ON

  - name: "iOS Xcode 10"
    os: osx
    osx_image: xcode10
    env:
     - CMAKE_FLAGS="-GXcode -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/iOS.toolchain.cmake -DBGFX_BUILD_TOOLS=OFF -DBGFX_BUILD_EXAMPLES=OFF"

  - name: "iOS Xcode 10 Amalgamated"
    os: osx
    osx_image: xcode10
    env:
     - CMAKE_FLAGS="-GXcode -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/iOS.toolchain.cmake -DBGFX_BUILD_TOOLS=OFF -DBGFX_BUILD_EXAMPLES=OFF"
     - AMALGAMATED=ON

  - name: "Visual studio 15 2017"
    os: windows
    env:
      - AMALGAMATED=ON
    

  - name: "Visual studio 15 2017 Amalgamated"
    os: windows
    env:
      - AMALGAMATED=ON

script:
  - mkdir build && cd build
  - cmake $CMAKE_FLAGS -DBGFX_INSTALL_EXAMPLES=ON -DBGFX_AMALGAMATED=$AMALGAMATED -DBX_AMALGAMATED=$AMALGAMATED ..
  - cmake --build .
